# Generated by Django 5.2.4 on 2025-09-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select country"),
                    ("US", "United States, Washington +1 202"),
                    ("IQ", "Iraq, Baghdad +964 1"),
                    ("GB", "United Kingdom, London +44 20"),
                    ("DE", "Germany, Berlin +49 30"),
                    ("FR", "France, Paris +33 1"),
                    ("LY", "Libya, Tripoli +218 21"),
                    ("AR", "Argentina, Buenos Aires +54 11"),
                    ("DZ", "Algeria, Algiers +213 21"),
                    ("CI", "Côte d'Ivoire, Abidjan +225 27"),
                    ("ZA", "South Africa, Cape Town +27 21"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
