services:
  postgres_account:
    image: postgres:17-bookworm
    container_name: auth_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5434"
    volumes:
      - pg_data_account_service:/var/lib/postgresql/data

volumes:
  pg_data_account_service: